### ISSUE TITLE
post regression summary in 1 issue

### ISSUE THREAD

**Issue by efiop** [iterative/dvc-bench#115]
This seems a bit too noisy. Do we need separate issues for each test?
![Screenshot from 2020-06-24 05-32-38](https://user-images.githubusercontent.com/5367102/85491400-22d46980-b5dc-11ea-81c3-c809798fff34.png)

**Comment by pared** [comment]
Created issue on the [rss action repository](https://github.com/guilhem/rss-issues-action/issues/4).
