### ISSUE TITLE
Introduce memory benchmarks

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#129]
Sample issue: https://discord.com/channels/485586884165107732/485596304961962003/727509738870538313

https://github.com/iterative/dvc/issues/4139

We should have a few memory usage benchmarks. 

Need to research whether it is possible to do both timing and memory measurement in single benchmark run.

**Comment by pared** [comment]
Worth noting, that in this case we should avoid [`setup` method](https://asv.readthedocs.io/en/stable/writing_benchmarks.html#peak-memory)

**Comment by daavoo** [comment]
This looks fancy: https://github.com/bloomberg/pytest-memray
