### ISSUE TITLE
nightly builds for dvc master

### ISSUE THREAD

**Issue by efiop** [iterative/dvc-bench#15]

**Comment by pared** [comment]
The main problem here is what is considered `night` in our team notion? ;)

**Comment by pared** [comment]
Probably will need to be solved with bot created for #13

**Comment by efiop** [comment]
@pared Just regular daily cron jobs.

**Comment by efiop** [comment]
@pared I would guess that bot is not required. Things like travis have that feature, so I suppose gh also can do that.

**Comment by skshetry** [comment]
We can create a package on a nightly basis and upload it to `testpypi` and then use those inside `dvc-bench`.
