### ISSUE TITLE
Error 5 Access is denied on Windows machine

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#184]
Upon running on my personal machine, I receive `Error 5: Access is denied` on `DVCIgnoreBench` `setup`.
Need to investigate whether it's my machine problem, or more general. So far it seems Github Actions don't have this problem. 
Might be due to us restricting windows version to `windows-2019`

**Comment by pared** [comment]
Might be related:
https://github.com/iterative/dvc/pull/5425

**Comment by efiop** [comment]
closing as stale
