### ISSUE TITLE
Write asv run to log file

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#22]
Write `run_benchmarks` repro output to log file and use `upload-action` to save it alongside benchmark results in actions artifacts.

**Comment by pared** [comment]
It seems like `asv` redirects  stderr to 1 when using `--show-stderr` option. So my initial idea which was to show 1 in run log as progress indicator and general summary, and write 2 to run log, for potential investigation, might not be viable idea.

**Comment by efiop** [comment]
No longer relevant with test-based parallelism, as it is actually easier to have full log at your disposal in gha, instead of having to download logs. Closing.
