### ISSUE TITLE
Investigate why benchmark cleanup does not work on windows

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#23]
In #17 we had to introduce file `chmod`-ding in order to be able to clean-up benchmark repos under the Windows. 

This is strange, as it seems that `TemporaryDirectory` should do that by itself:
https://github.com/python/cpython/blob/fa919fdf2583bdfead1df00e842f24f30b2a34bf/Lib/tempfile.py#L792

Investigate why do we receive WinError 5 (Access Denied) on windows runner upon benchmark directory cleanup.

**Comment by efiop** [comment]
Closing as stale.
