### ISSUE TITLE
extend dvc-bench as a test harness? 

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc-bench#241]
`dvc-bench` is meant to be a macro level benchmark testing high level scenarios. But, we are also testing micro benchmarks here (eg. startup, init), as the infrastructure it provides is great. 

The problem though is that we'd like to find out regressions in those micro benchmarks in the same PR before merging it. Otherwise, we'd waste too much time figuring out the root cause, and we'll always regress. (Eg: init/startup right now).

So, I'd propose that we:
1. Either keep micro benchmarks in the DVC's own repo and run them on each PR.
2. Or, keep using dvc-bench, but extend it to facilitate be able to run it somehow on each PR in the DVC (only for micro benchmarks). This could be in the form of hooks or in some form of bash scripts that makes bootstrapping it easier. (It could be packaged into github actions as well if possible 😂)

**Comment by shcheklein** [comment]
@skshetry an idea. can we run it daily and react accordingly? we don't have _that_ many PRs merged per day. It sounds tempting to run some basic part on PR CI though

**Comment by skshetry** [comment]
@shcheklein, I think we do run it daily. I think it'd be better to prevent regressions, rather than chasing it every time.

For example, for startup time to degrade, it just takes one slow import somewhere. So, I always expect it to regress (it already has). Figuring that out takes a lot of time. 

I am only asking for something like follows in the dvc-bench:
```console
$ git clone dvc-bench
$ cd dvc-bench && run_benchmarks.sh
```
