### ISSUE TITLE
add cloud benchmarks

### ISSUE THREAD

**Issue by efiop** [iterative/dvc-bench#252]
An umbrella issue for push/pull/etc benches for different clouds (mostly for the most important ones, no need to test every weird cloud). Related: https://github.com/iterative/dvc-bench/issues/246

- [x] s3
- [ ] gs
- [ ] azure
- [ ] ssh

Also, important to have end-to-end tests that make sure that data didn't get corrupted after push/pull.

**Comment by dberenbaum** [comment]
As mentioned in https://discord.com/channels/485586884165107732/485596304961962003/831500146772148244, s5cmd might be a good benchmark for s3.

**Comment by dberenbaum** [comment]
Also, rsync might be a good one for ssh: https://discord.com/channels/485586884165107732/563406153334128681/838714168420073523

**Comment by isidentical** [comment]
Ruslan and I talked about this and decided to prioritize it. Regarding the actual implementation, I was exploring the options and noticed that there is already support for parametrized benchmarks in asv so I guess that would be the way forward: https://asv.readthedocs.io/en/stable/writing_benchmarks.html#parametrized-benchmarks. 

> The parameter values can be any Python objects. However, it is often best to use only strings or numbers, because these have simple unambiguous text representations.

I think the parameters are displayed in the web UI (?) so it would be better to give parameters as `['s3', 'gs', 'azure']` etc. and give the actual settings (like the `url`, credentials etc) separately in the setup. We could prepare a JSON file similar to this;
```
{
   's3': {
        'x': 'y'
   },
   'gs': {
      'y': 'z'
   },
   'azure': {
      'u': 'q'
   }
}
```

and dump it to `remotes.json`. Each test would be responsible with configuring those (and probably share a common `setup()` method to do so). Other than that I don't expect to see major changes on the actual implementation of benchmarks.

**Comment by pared** [comment]
@karajan1001 you mentioned that it would be good to have oss benchmarks? Should we reopen this issue?

**Comment by karajan1001** [comment]
@pared , As there wasn't so much user with oss, and a new cloud benchmark test took so much time, I don't think we need to add it to the daily tests benchmark. But I still need some tests for the new fs's performance. So maybe the dvc-bench needs to be divided into serval different levels, some of them were those we mainly focused on, while the others would only be tested when some big changes were done or there were users' complain about them.

**Comment by pared** [comment]
@karajan1001 this is a good idea, though we probably don't have enough capacity to take care of that soon. Still I think we could aim for that at some point. Would you create issue for that, or can I do that?
