### ISSUE TITLE
Memory usage related benchmarks

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc-bench#264]
While checking out the asv documentation I noticed that it also supports different sorts of benchmarks (more precisely, memory-related stuff). In the past, we've seen some memory-related issues and tried to resolve them and benchmark the usages manually (e.g checking the memory usage every 2 seconds and preparing a graph), e.g https://github.com/iterative/dvc/issues/4139. But I think it might be nice if we also start writing some memory benchmarks (especially for push/pull and maybe even `import-url --to-remote` to guarantee that is not trying to load everything into memory). I didn't particularly test the memory usages while I was migrating to fsspec so there might be stuff that we might notice due to those changes too (maybe dir cache is wasting a lot of memory? or there is a subtle bug in the chunked read etc). 

CC: @pared @efiop 

https://asv.readthedocs.io/en/stable/benchmarks.html

**Comment by pared** [comment]
@isidentical we have an issue for that:
https://github.com/iterative/dvc-bench/issues/129
closing in favour of that one :)

**Comment by isidentical** [comment]
Ah, great!
