### ISSUE TITLE
runner: upgrade to a machine with better network?

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc-bench#280]
It seem like `t3a.large` has only 5gbit bandwidth, I know that DVC can't particularly use all of the bandwidth for certain providers (e.g S3) but still I believe it might make things run a bit faster. See https://instances.vantage.sh/ for network comparison on different machines

**Comment by isidentical** [comment]
CC: @pared @efiop

**Comment by pared** [comment]
@isidentical 
I think we could consider that. Also my favourite seems to be `z1d.large`. We would get 2x bandwithd, 2x ram and also we would get fastest possible  single-core performance, which could speed up our builds. We could focus on that untill we figure out how to parallelize our builds.

**Comment by isidentical** [comment]
Looks great.

**Comment by pared** [comment]
Though, while we can benefit from chaning the machine, I would consider the aim of this issue to check if we actually have problem. Proper monitoring would also help us with cpu concerns from #281  

We should probably setup monitoring for the runner machine. I haven't done that yet, so marking the issue as research.
cc @isidentical

**Comment by pared** [comment]
Currently we are basing the tests on free runners, and don't have a control over their setup as we used pre #294. Closing for now.
