### ISSUE TITLE
runner: research parallel build

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#281]
Asv gives a lot of potential when it comes to build paralellization.
So far we are using 2 core processor for our benchmarks, and make build with single core. 
Since we are creating more benchmarks and build can take now even 6 hours.
We could upgrade the machine to multi-core one and parallelize the build,
but before doing that we should consider few things, for example:
- [ ] can benchmarks parallelization influence bandwidth-using benchmarks?
- [ ] in benchmarks using `--jobs`: how to estimate required cpus to make sure build parallelization won't affect benchmarks results

Related #280 
cc @isidentical

**Comment by efiop** [comment]
>  can benchmarks parallelization influence bandwidth-using benchmarks?

For sure it will.

So maybe better to parallelize the tests across machines? We really care about machine consistency within one test, nothing more, so maybe we could run extremely long running tests on separate machines and then assemble the results?

**Comment by pared** [comment]
@efiop 
We should be able to do it relatively easy, benchmarks can be matched in `run` with regex, so we should be able to do that.

**Comment by efiop** [comment]
For the record: discussed with @pared that for simplicity, it might be better to reduce the size of datasets for now and use github actions for development, so that we don't have to mess with infrastructure right away. After we are all set, we could then get back to  using our more powerful runners.
