### ISSUE TITLE
results: how to get errors

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#283]
in #277 we didn't get `gc` benchmark results because they were silently timing out. Research if its possible to return failed benchmarks after run.

**Comment by pared** [comment]
#284 Is a result of asv dismissing errors. On one hand this is a feature, because it allows us to run all the benchmarks even if some problem occurs. On the other hand we silently ignore actual problems.

**Comment by efiop** [comment]
Might be fixed by https://github.com/iterative/dvc-bench/issues/294

**Comment by pared** [comment]
`pytest` based benchmarks behave like tests, so indeed #294 seemed to fix the issue. Currently, if we have some problems, the build fails.
