### ISSUE TITLE
Unwrap remote URLs for update benchmarks

### ISSUE THREAD

**Issue by isidentical** [iterative/dvc-bench#284]
It seems like we are passing the wrapped url (with `remote://<remote name>/...`) directly to the fsspec, which doesn't work. We should pass the original URL (`bucket/something/something`) instead of the reduced DVC form (`remote://storage/something`). 
https://github.com/iterative/dvc-bench/blob/8c4d9c066c47be6bfe6600a35596492755b67a7e/benchmarks/update.py#L22

**Comment by pared** [comment]
That is the reason for lack of results for update benchmarks.
Related to #283
