### ISSUE TITLE
migrate to pytest-benchmark

### ISSUE THREAD

**Issue by efiop** [iterative/dvc-bench#294]
- [x] basic test migration
- [ ] test parity with old (e.g. what do we do with remote tests? Should they be here or maybe in every individual plugin?)
- [ ] notify about regressions
- [ ] cleanup leftovers

**Comment by pared** [comment]
@efiop seems like after https://github.com/iterative/dvc-bench/pull/296 we can close it?

**Comment by efiop** [comment]
> [ verbose description WIP ]

Oh wow, looks like closed the tab or something 🤦 

There are a few more steps here before we can close it. Added a checklist.
