### ISSUE TITLE
Benchmark `--jobs`.

### ISSUE THREAD

**Issue by daavoo** [iterative/dvc-bench#316]
It would be nice to benchmark the performance of non-default `--jobs` for commands that support it and also `core.checksum_jobs`.

**Comment by dtrifiro** [comment]
Doing some preliminary testing in #321

**Comment by efiop** [comment]
For the record: discussed with @daavoo that it might be wasteful to test it like that. We might be better off testing defaults right now and waiting for auto-throttling (automatic, by every fs implementation).
