### ISSUE TITLE
Investigate whether there is a point in running our benchmarks with `--profile` option

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#33]
It is possible that there is no point in running the benchmarks with `--profile` option, since, [cProfile results might not be portable](https://asv.readthedocs.io/en/stable/using.html#running-a-benchmark-in-the-profiler). We need to verify that and turn off profiling if we cannot use its results.

**Comment by efiop** [comment]
@pared The data is not useful for the asv itself, hence why they mention abs paths in the doc. But it is still useful for us, that's why we ask people to provide profiler report and we have no trouble viewing it on our own machines.

**Comment by pared** [comment]
@efiop 
right, closing for now
