### ISSUE TITLE
bench exp run failing

### ISSUE THREAD

**Issue by dtrifiro** [iterative/dvc-bench#368]
the experiment benchmarks are currently failing because the `dvc` branch of https://github.com/dberenbaum/lstm_seq2seq does not have a configured remote

**Comment by efiop** [comment]
Was meaning to fix this a few days ago, but got distracted. Will take a look.

**Comment by efiop** [comment]
Tried using https://github.com/iterative/example-dvc-experiments too, but the fact that we need to install heavy weight requirements to run the pipeline makes me second guess if we really need this. Removed that test for now, we'll probably get back to it later.
