### ISSUE TITLE
Do not build when merging to master

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#40]
Currently, wokflow is as follows:
1. Prepare PR -> GHA builds it
2. Build successful, review done -> merge to master
3. Another build is triggered, on master this time. In this case only difference between PR build is that we deploy html to gh-pages branch. 

What should happen: After merge, get html from PR build and publish it to gh-pages.

**Comment by efiop** [comment]
@pared It should work automatically if we store the results for the benchmarks. We shouldn't really keep html as the final artifact, but rather the raw benchmark results that we can then visualize. Or am I missing something?

**Comment by efiop** [comment]
Seems like you are doing precisely that in https://github.com/iterative/dvc-bench/pull/37/files .

After we store the results in dvc, the build will be started after the merge, but it will see that there is nothing to do and will just show the results from the previous runs.

**Comment by pared** [comment]
@efiop you are right, proper usage of DVC should handle this. Will close it after #38 is fixed.
