### ISSUE TITLE
cloud versioning

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc-bench#408]
Add benchmarks for cloud versioning remotes

**Comment by efiop** [comment]
Might be worth putting these per every plugin (e.g. into dvc-s3 for s3) and test particular functionality (like index building). Testing all clouds in `dvc-bench` might be an overkill, this didn't work out well with previous version of dvc-bench.

**Comment by dberenbaum** [comment]
True, that could be nice, but I was thinking of just testing in s3 like we do for regular remotes to make sure the basic workflow has reasonable benchmarks in line with traditional remotes.

**Comment by dberenbaum** [comment]
Sorry, my mistake here. I guess we don't test s3 for regular remotes with dvc-bench now. So maybe we either need to test on at least one cloud remote or indeed move this to each plugin.

**Comment by efiop** [comment]
Though we have the infra in dvc-bench for running with different clouds, so maybe should fit in here after all.
