### ISSUE TITLE
Migrate to DVC 1.0

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#61]
Currently, `dvc-bench` uses `0.94.0`. Migrate after `1.0` is released.

**Comment by skshetry** [comment]
Try with this gist when 1.0 releases, if you don't want to do it manually: https://gist.github.com/skshetry/07a3e26e6b06783e1ad7a4b6db6479da

```console
$ ./migrator.py run_benchmarks.dvc run_benchmarks
$ ./migrator.py convert_tags.dvc convert_tags
```

**Comment by pared** [comment]
@skshetry thank you very much!

**Comment by pared** [comment]
Fixed by https://github.com/iterative/dvc-bench/pull/127
