### ISSUE TITLE
Make full build on pull_request

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#62]
After #60 "full" build with results reusing is possible only on master. In #60 we discussed possible steps that could be taken to make build upon pull_request. Also, might be related to #61.

As for now ideas are:
- use github artifacts to store and reuse the results
- prepare staging branch, that will be responsible for a full build, which is not a perfect solution (only if we run on PR we can be sure that change is correct, but at least lets us avoid hussle of fixing master)
-  make remote accessible for PR changes, in one way or another (eg read-only)

**Comment by efiop** [comment]
Fixed by https://github.com/iterative/dvc-bench/pull/293
