### ISSUE TITLE
github actions: get rid of results PR

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#70]
As of today workflow is as follows: 
1. Prepare change
2. Create PR
3. Get accepted -> build
4. PR to `run_benchmarks.dvc` with updated directory checksum.

Point 4 does not make sense, as there is not too much one can review just looking at the change on `dvc-bench` repository. Maybe we should push instead of creating PR.

Automatically pushing to master might not be the best idea, so we could consider the `pre-master` branch.

**Comment by efiop** [comment]
If me migrate to 1.0 https://github.com/iterative/dvc-bench/issues/61 , then we could leverage run-cache, that will make us not need to commit at all, if we can provide deterministic dependencies.

**Comment by pared** [comment]
Related to #61
