### ISSUE TITLE
benchmark: add dvc repo with 20000 stages/dvcfiles

### ISSUE THREAD

**Issue by efiop** [iterative/dvc-bench#73]
SC use case.

**Comment by skshetry** [comment]
We should start with 10-100 stages for now, 20000 stages to always test is crazy. The "levels of 10" benchmarks should give us pretty good results, which we can extrapolate to 20000. It is just too much.

**Comment by efiop** [comment]
For the record: need to get back to this after pytest-benchmark migration, we need to start with making `dataset` testing comfy first and then we could do the same for `dag` https://github.com/iterative/dvc-bench/issues/294
