### ISSUE TITLE
Ping engineering on noticable performance degradation

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#8]
Create action/script/magic that will inform iterative/engineering team when recent tag introduced noticable degradation (eg 20% increase in time).

Some notes:
- so far we are uploading only html page as results of our github actions job, maybe we should actually upload `results` (which contain benchmark results as JSON's), and leave HTML for deploy only. JSON's could be used as a base to job calculating degradation and sending email, if necessary.
- `asv` produces recent degradation info [here](https://iterative.github.io/dvc-bench/#summarylist).

**Comment by efiop** [comment]
And/or a p0/p1 ticket, as suggested in https://github.com/iterative/dvc/issues/2511

**Comment by pared** [comment]
Ok, so first point: thanks to @skshetry for noticing the Atom feed available in `asv`.
We can utilize it and Atom reader to ping us on our chat.

The `regressions` finding algorithm can be adjusted with `asv.conf.json`.
By default, single step degradation by 5 % will be considered as a reason to publish new update in Atom feed. Regression threshold values can be adjusted per single benchmark via `asv.conf.json`. 
Since we already use our chat to ping engineering on what happens in discuss, I think we could simply use RSS reader, and that would be pretty much it.
