### ISSUE TITLE
Find a way to store/present profiling data

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#9]
`asv run` contains `--profile` option which, besides running benchmarks in `normal` way 10 times, profiles the benchmarks too.

This task can be solved in few ways:
- include snakeviz visualizations in static webpage content uploaded to iterative.github.io/dvc-bench
- include snakeviz visualization/cProfile results and attach them to ping from #8

**Comment by efiop** [comment]
snakeviz requires some effort to make the report static https://gist.github.com/jiffyclub/6b5e0f0f05ab487ff607 . Maybe not worth bothering at this point.

But at least including the results would be nice.

**Comment by efiop** [comment]
collecting profiling data results in an overhead and is generally not needed until we actually run into problems, but when we do - we'll just run proper profilers (cprofile, yappi, etc) granularly. Closing.
