### ISSUE TITLE
runners: investigate whether its possible to get constatnt machines

### ISSUE THREAD

**Issue by pared** [iterative/dvc-bench#91]

**Comment by skshetry** [comment]
@pared, let's use our own runner instead. Let's not waste time on this, what do you say?

**Comment by pared** [comment]
@skshetry that makes sense, thought I think @pmrowla mentioned it is possible, and I forget to check, so I created this issue as a reminder. If it will be too much work, lets just use our own.

**Comment by pmrowla** [comment]
Yeah, I meant that it's possible to setup our own runners with github actions

https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners

**Comment by pared** [comment]
Closing for now. We discussed that we should consider applying regression thresholds for unreliable machines. Need to see if that is possible on asv side/ prepare PR for that.
